# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  - mavenDeploy

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

# Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

#basically builds, then copies the jar to the /target folder, then stops existing service, and finally restarts it.


android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - cd MainApp
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - cd MainApp
    - ./gradlew test


